name: App Inspect API

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    appinspect:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - uses: actions/cache@v1
              with:
                  path: node_modules
                  key: nodeModules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      nodeModules-
            - name: Update Version Number
              run: |
                old_str="X.Y.Z"
                new_str=$(echo "${GITHUB_REF#refs/*/}" | tr -d "v")
                sed -i "s/$old_str/$new_str/g" package.json
                sed -i "s/$old_str/$new_str/g" ./${{ vars.appName }}/default/app.conf
                cat package.json
                cat ./${{ vars.appName }}/default/app.conf
            - name: Install dependencies
              run: yarn install
              env:
                  CI: true
            - name: Build app package
              run: |
                  yarn package
                  mv dist/*.spl dist/${{ vars.appName }}.spl
            - uses: actions/upload-artifact@v1
              with:
                  name: app-package
                  path: dist/${{ vars.appName }}.spl
            - uses: ./.github/actions/appinspect_api
              with:
                  filePath: ./dist/${{ vars.appName }}.spl
                  splunkUser: ${{ secrets.SPLUNKBASE_USER }}
                  splunkPassword: ${{ secrets.SPLUNKBASE_PASSWORD }}
                  includedTags: cloud
            - name: Release
              uses: fnkr/github-action-ghr@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GHR_PATH: ./dist/${{ vars.appName }}.spl
                  GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
